version: "3.8"
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    volumes:
      - database:/var/lib/mysql
    env_file: .env
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  database: